name: Erlang CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erlang: [20, 21, 22, 23, 24, 25]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v2
      env:
        cache-name: rebar3
      with:
        path: |
          ~/.cache/rebar3
          _build
        key: ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3-${{hashFiles('rebar.lock')}}
        restore-keys: |
          ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}-rebar3
          ci-${{runner.os}}-${{env.cache-name}}-erlang_${{matrix.erlang}}
    - name: Compile
      run: rebar3 do clean, compile
    - name: Checks
      run: rebar3 check
    - name: Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: rebar3 as test coveralls send

